# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Hus_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(843, 369)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 80, 51, 21))
        self.label_3.setObjectName("label_3")
        self.pb_start = QtWidgets.QPushButton(Dialog)
        self.pb_start.setGeometry(QtCore.QRect(720, 170, 101, 31))
        self.pb_start.setObjectName("pb_start")
        self.pb_b14 = QtWidgets.QPushButton(Dialog)
        self.pb_b14.setGeometry(QtCore.QRect(190, 270, 61, 61))
        self.pb_b14.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b14.setObjectName("pb_b14")
        self.pb_b07 = QtWidgets.QPushButton(Dialog)
        self.pb_b07.setGeometry(QtCore.QRect(610, 200, 61, 61))
        self.pb_b07.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b07.setObjectName("pb_b07")
        self.pb_b05 = QtWidgets.QPushButton(Dialog)
        self.pb_b05.setGeometry(QtCore.QRect(470, 200, 61, 61))
        self.pb_b05.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b05.setObjectName("pb_b05")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(720, 290, 51, 21))
        self.label_6.setObjectName("label_6")
        self.pb_a08 = QtWidgets.QPushButton(Dialog)
        self.pb_a08.setGeometry(QtCore.QRect(610, 100, 61, 61))
        self.pb_a08.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a08.setObjectName("pb_a08")
        self.pb_b13 = QtWidgets.QPushButton(Dialog)
        self.pb_b13.setGeometry(QtCore.QRect(260, 270, 61, 61))
        self.pb_b13.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b13.setObjectName("pb_b13")
        self.pb_b09 = QtWidgets.QPushButton(Dialog)
        self.pb_b09.setGeometry(QtCore.QRect(540, 270, 61, 61))
        self.pb_b09.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b09.setObjectName("pb_b09")
        self.pb_a15 = QtWidgets.QPushButton(Dialog)
        self.pb_a15.setGeometry(QtCore.QRect(120, 100, 61, 61))
        self.pb_a15.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a15.setObjectName("pb_a15")
        self.pb_b03 = QtWidgets.QPushButton(Dialog)
        self.pb_b03.setGeometry(QtCore.QRect(330, 200, 61, 61))
        self.pb_b03.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b03.setObjectName("pb_b03")
        self.pb_a00 = QtWidgets.QPushButton(Dialog)
        self.pb_a00.setGeometry(QtCore.QRect(120, 30, 61, 61))
        self.pb_a00.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a00.setObjectName("pb_a00")
        self.pb_a12 = QtWidgets.QPushButton(Dialog)
        self.pb_a12.setGeometry(QtCore.QRect(330, 100, 61, 61))
        self.pb_a12.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a12.setObjectName("pb_a12")
        self.pb_a10 = QtWidgets.QPushButton(Dialog)
        self.pb_a10.setGeometry(QtCore.QRect(470, 100, 61, 61))
        self.pb_a10.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a10.setObjectName("pb_a10")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 250, 51, 21))
        self.label_4.setObjectName("label_4")
        self.pb_a09 = QtWidgets.QPushButton(Dialog)
        self.pb_a09.setGeometry(QtCore.QRect(540, 100, 61, 61))
        self.pb_a09.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a09.setObjectName("pb_a09")
        self.pb_a01 = QtWidgets.QPushButton(Dialog)
        self.pb_a01.setGeometry(QtCore.QRect(190, 30, 61, 61))
        self.pb_a01.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a01.setObjectName("pb_a01")
        self.pb_a04 = QtWidgets.QPushButton(Dialog)
        self.pb_a04.setGeometry(QtCore.QRect(400, 30, 61, 61))
        self.pb_a04.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a04.setObjectName("pb_a04")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 50, 51, 21))
        self.label.setObjectName("label")
        self.pb_b10 = QtWidgets.QPushButton(Dialog)
        self.pb_b10.setGeometry(QtCore.QRect(470, 270, 61, 61))
        self.pb_b10.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b10.setObjectName("pb_b10")
        self.pb_b11 = QtWidgets.QPushButton(Dialog)
        self.pb_b11.setGeometry(QtCore.QRect(400, 270, 61, 61))
        self.pb_b11.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b11.setObjectName("pb_b11")
        self.pb_b02 = QtWidgets.QPushButton(Dialog)
        self.pb_b02.setGeometry(QtCore.QRect(260, 200, 61, 61))
        self.pb_b02.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b02.setObjectName("pb_b02")
        self.pb_a02 = QtWidgets.QPushButton(Dialog)
        self.pb_a02.setGeometry(QtCore.QRect(260, 30, 61, 61))
        self.pb_a02.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a02.setObjectName("pb_a02")
        self.pb_a07 = QtWidgets.QPushButton(Dialog)
        self.pb_a07.setGeometry(QtCore.QRect(610, 30, 61, 61))
        self.pb_a07.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a07.setObjectName("pb_a07")
        self.pb_b12 = QtWidgets.QPushButton(Dialog)
        self.pb_b12.setGeometry(QtCore.QRect(330, 270, 61, 61))
        self.pb_b12.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b12.setObjectName("pb_b12")
        self.pb_b01 = QtWidgets.QPushButton(Dialog)
        self.pb_b01.setGeometry(QtCore.QRect(190, 200, 61, 61))
        self.pb_b01.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b01.setObjectName("pb_b01")
        self.pb_a06 = QtWidgets.QPushButton(Dialog)
        self.pb_a06.setGeometry(QtCore.QRect(540, 30, 61, 61))
        self.pb_a06.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a06.setObjectName("pb_a06")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(720, 90, 51, 21))
        self.label_5.setObjectName("label_5")
        self.pb_b04 = QtWidgets.QPushButton(Dialog)
        self.pb_b04.setGeometry(QtCore.QRect(400, 200, 61, 61))
        self.pb_b04.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b04.setObjectName("pb_b04")
        self.pb_a14 = QtWidgets.QPushButton(Dialog)
        self.pb_a14.setGeometry(QtCore.QRect(190, 100, 61, 61))
        self.pb_a14.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a14.setObjectName("pb_a14")
        self.pb_b06 = QtWidgets.QPushButton(Dialog)
        self.pb_b06.setGeometry(QtCore.QRect(540, 200, 61, 61))
        self.pb_b06.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b06.setObjectName("pb_b06")
        self.pb_b00 = QtWidgets.QPushButton(Dialog)
        self.pb_b00.setGeometry(QtCore.QRect(120, 200, 61, 61))
        self.pb_b00.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b00.setObjectName("pb_b00")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 220, 51, 21))
        self.label_2.setObjectName("label_2")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(720, 60, 51, 21))
        self.label_8.setObjectName("label_8")
        self.pb_a05 = QtWidgets.QPushButton(Dialog)
        self.pb_a05.setGeometry(QtCore.QRect(470, 30, 61, 61))
        self.pb_a05.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a05.setObjectName("pb_a05")
        self.pb_b08 = QtWidgets.QPushButton(Dialog)
        self.pb_b08.setGeometry(QtCore.QRect(610, 270, 61, 61))
        self.pb_b08.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b08.setObjectName("pb_b08")
        self.pb_a11 = QtWidgets.QPushButton(Dialog)
        self.pb_a11.setGeometry(QtCore.QRect(400, 100, 61, 61))
        self.pb_a11.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a11.setObjectName("pb_a11")
        self.pb_a03 = QtWidgets.QPushButton(Dialog)
        self.pb_a03.setGeometry(QtCore.QRect(330, 30, 61, 61))
        self.pb_a03.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a03.setObjectName("pb_a03")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(720, 260, 51, 21))
        self.label_7.setObjectName("label_7")
        self.pb_a13 = QtWidgets.QPushButton(Dialog)
        self.pb_a13.setGeometry(QtCore.QRect(260, 100, 61, 61))
        self.pb_a13.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_a13.setObjectName("pb_a13")
        self.pb_b15 = QtWidgets.QPushButton(Dialog)
        self.pb_b15.setGeometry(QtCore.QRect(120, 270, 61, 61))
        self.pb_b15.setStyleSheet("QPushButton {\n"
"color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 30px;\n"
"border-style: outset;\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888\n"
");\n"
"padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background: qradialgradient(\n"
"cx: 0.3, cy: -0.4, fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #bbb\n"
");\n"
"}")
        self.pb_b15.setObjectName("pb_b15")
        self.l_handstones = QtWidgets.QLabel(Dialog)
        self.l_handstones.setGeometry(QtCore.QRect(120, 160, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_handstones.setFont(font)
        self.l_handstones.setAlignment(QtCore.Qt.AlignCenter)
        self.l_handstones.setObjectName("l_handstones")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "0"))
        self.pb_start.setText(_translate("Dialog", "Start"))
        self.pb_b14.setText(_translate("Dialog", "0"))
        self.pb_b07.setText(_translate("Dialog", "0"))
        self.pb_b05.setText(_translate("Dialog", "0"))
        self.label_6.setText(_translate("Dialog", "0"))
        self.pb_a08.setText(_translate("Dialog", "0"))
        self.pb_b13.setText(_translate("Dialog", "0"))
        self.pb_b09.setText(_translate("Dialog", "0"))
        self.pb_a15.setText(_translate("Dialog", "0"))
        self.pb_b03.setText(_translate("Dialog", "0"))
        self.pb_a00.setText(_translate("Dialog", "0"))
        self.pb_a12.setText(_translate("Dialog", "0"))
        self.pb_a10.setText(_translate("Dialog", "0"))
        self.label_4.setText(_translate("Dialog", "0"))
        self.pb_a09.setText(_translate("Dialog", "0"))
        self.pb_a01.setText(_translate("Dialog", "0"))
        self.pb_a04.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "Punkte"))
        self.pb_b10.setText(_translate("Dialog", "0"))
        self.pb_b11.setText(_translate("Dialog", "0"))
        self.pb_b02.setText(_translate("Dialog", "0"))
        self.pb_a02.setText(_translate("Dialog", "0"))
        self.pb_a07.setText(_translate("Dialog", "0"))
        self.pb_b12.setText(_translate("Dialog", "0"))
        self.pb_b01.setText(_translate("Dialog", "0"))
        self.pb_a06.setText(_translate("Dialog", "0"))
        self.label_5.setText(_translate("Dialog", "0"))
        self.pb_b04.setText(_translate("Dialog", "0"))
        self.pb_a14.setText(_translate("Dialog", "0"))
        self.pb_b06.setText(_translate("Dialog", "0"))
        self.pb_b00.setText(_translate("Dialog", "0"))
        self.label_2.setText(_translate("Dialog", "Punkte"))
        self.label_8.setText(_translate("Dialog", "Steine"))
        self.pb_a05.setText(_translate("Dialog", "0"))
        self.pb_b08.setText(_translate("Dialog", "0"))
        self.pb_a11.setText(_translate("Dialog", "0"))
        self.pb_a03.setText(_translate("Dialog", "0"))
        self.label_7.setText(_translate("Dialog", "Steine"))
        self.pb_a13.setText(_translate("Dialog", "0"))
        self.pb_b15.setText(_translate("Dialog", "0"))
        self.l_handstones.setText(_translate("Dialog", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
