# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqtcss.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CSSTest(object):
    def setupUi(self, CSSTest):
        CSSTest.setObjectName("CSSTest")
        CSSTest.resize(244, 412)
        self.centralwidget = QtWidgets.QWidget(CSSTest)
        self.centralwidget.setObjectName("centralwidget")
        self.pbOben = QtWidgets.QPushButton(self.centralwidget)
        self.pbOben.setGeometry(QtCore.QRect(90, 100, 80, 80))
        self.pbOben.setObjectName("pbOben")
        self.pbUnten = QtWidgets.QPushButton(self.centralwidget)
        self.pbUnten.setGeometry(QtCore.QRect(90, 230, 80, 80))
        self.pbUnten.setObjectName("pbUnten")
        CSSTest.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CSSTest)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 244, 21))
        self.menubar.setObjectName("menubar")
        CSSTest.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CSSTest)
        self.statusbar.setObjectName("statusbar")
        CSSTest.setStatusBar(self.statusbar)

        self.pbOben.clicked.connect(self.obenCB)
        self.pbUnten.clicked.connect(self.untenCB)

        self.retranslateUi(CSSTest)
        QtCore.QMetaObject.connectSlotsByName(CSSTest)

    def retranslateUi(self, CSSTest):
        _translate = QtCore.QCoreApplication.translate
        CSSTest.setWindowTitle(_translate("CSSTest", "CSS Test"))
        self.pbOben.setText(_translate("CSSTest", "PushButton"))
        self.pbUnten.setText(_translate("CSSTest", "PushButton"))


    def obenCB(self):
        self.pbOben.setStyleSheet("border-radius : 40; border : 2px solid black; background-color: green")
        self.pbOben.setText("40")
        self.pbUnten.setStyleSheet("border-radius : 10; border : 2px solid black; background-color: red")
        self.pbUnten.setText("10")

    def untenCB(self):
        self.pbUnten.setStyleSheet("border-radius : 40; border : 2px solid black; background-color: green")
        self.pbUnten.setText("40")
        self.pbOben.setStyleSheet("border-radius : 10; border : 2px solid black; background-color: red")
        self.pbOben.setText("10")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CSSTest = QtWidgets.QMainWindow()
    ui = Ui_CSSTest()
    ui.setupUi(CSSTest)
    CSSTest.show()
    sys.exit(app.exec_())
